#!/bin/bash
# Build a notarized, stapled StockAlerts DMG ready to share.
#
# Local-only release pipeline (the CI release workflow is a follow-up). Runs the
# standard Apple distribution chain end to end:
#
#   xcodegen generate
#     -> xcodebuild archive            (Release)
#     -> xcodebuild -exportArchive     (Developer ID, automatic signing)
#     -> xcrun notarytool submit --wait
#     -> xcrun stapler staple <app>
#     -> create-dmg                    (signed)
#     -> xcrun stapler staple <dmg>
#     -> spctl --assess                (verify)
#
# Output: dist/StockAlerts-<version>.dmg, where <version> is read from the built
# app's CFBundleShortVersionString (never hand-typed here).
#
# Each stage is a named function so a failure points at the exact step.
#
# Requires (see documentation/release.md for one-time setup):
#   - Local.xcconfig (DEVELOPMENT_TEAM) — same file scripts/test.sh uses
#   - create-dmg               (brew install create-dmg)
#   - xcodegen                 (brew install xcodegen)
#   - a "Developer ID Application" identity in the login keychain
#   - a saved notary credential profile (default name: stockalerts-notary),
#     overridable with STOCKALERTS_NOTARY_PROFILE
#
# DMG window layout assets live in dmg-assets/ (background.png is generated by
# scripts/generate-dmg-background.swift — run rarely, not from here).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
BUILD_DIR="$REPO_ROOT/build"
DIST_DIR="$REPO_ROOT/dist"
ARCHIVE_PATH="$BUILD_DIR/StockAlerts.xcarchive"
EXPORT_DIR="$BUILD_DIR/export"
APP_PATH="$EXPORT_DIR/StockAlerts.app"
EXPORT_PLIST="$BUILD_DIR/ExportOptions.plist"
TEMPLATE_PLIST="$SCRIPT_DIR/ExportOptions.template.plist"
BACKGROUND="$REPO_ROOT/dmg-assets/background.png"
NOTARY_PROFILE="${STOCKALERTS_NOTARY_PROFILE:-stockalerts-notary}"

# Filled in by preflight / read_version.
DEV_TEAM=""
SIGN_IDENTITY=""
VERSION=""

log() { echo "==> $*"; }
fail() { echo "Error: $*" >&2; exit 1; }

preflight() {
    log "Preflight"

    if [ ! -f "$REPO_ROOT/Local.xcconfig" ]; then
        cat >&2 <<EOF
Error: Local.xcconfig not found in $REPO_ROOT

  cp Local.xcconfig.example Local.xcconfig
  # then edit it to set DEVELOPMENT_TEAM to your Apple team ID

See README.md / documentation/release.md for details.
EOF
        exit 1
    fi

    DEV_TEAM="$(grep -E '^[[:space:]]*DEVELOPMENT_TEAM[[:space:]]*=' "$REPO_ROOT/Local.xcconfig" \
        | head -1 | sed -E 's/^[^=]*=[[:space:]]*//' | tr -d '[:space:]')"
    [ -n "$DEV_TEAM" ] || fail "DEVELOPMENT_TEAM is empty in Local.xcconfig"

    command -v xcodegen >/dev/null 2>&1 || fail "xcodegen not found — brew install xcodegen"
    command -v create-dmg >/dev/null 2>&1 || fail "create-dmg not found — brew install create-dmg"
    [ -f "$BACKGROUND" ] || fail "DMG background missing at $BACKGROUND — run: swift scripts/generate-dmg-background.swift"

    SIGN_IDENTITY="$(security find-identity -v -p codesigning \
        | grep "Developer ID Application" | head -1 | sed -E 's/.*"(.*)".*/\1/')"
    [ -n "$SIGN_IDENTITY" ] || fail "No \"Developer ID Application\" identity in the keychain. See documentation/release.md."
    log "Signing identity: $SIGN_IDENTITY"

    # Validates the notary credential profile exists (and the network path works).
    if ! xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null 2>&1; then
        fail "Notary profile '$NOTARY_PROFILE' not usable. Save it with:
  xcrun notarytool store-credentials $NOTARY_PROFILE --key <AuthKey.p8> --key-id <id> --issuer <issuer-uuid>
See documentation/release.md (override the name with STOCKALERTS_NOTARY_PROFILE)."
    fi
}

generate_project() {
    log "Generate Xcode project (xcodegen)"
    ( cd "$REPO_ROOT" && xcodegen generate )
}

render_export_options() {
    log "Render export options (team $DEV_TEAM)"
    mkdir -p "$BUILD_DIR"
    sed "s/__DEVELOPMENT_TEAM__/$DEV_TEAM/g" "$TEMPLATE_PLIST" > "$EXPORT_PLIST"
}

archive() {
    log "Archive (Release)"
    rm -rf "$ARCHIVE_PATH"
    xcodebuild \
        -project "$REPO_ROOT/StockAlerts.xcodeproj" \
        -scheme StockAlerts \
        -configuration Release \
        -destination 'platform=macOS,arch=arm64' \
        -archivePath "$ARCHIVE_PATH" \
        -allowProvisioningUpdates \
        archive
}

export_app() {
    log "Export archive (Developer ID)"
    rm -rf "$EXPORT_DIR"
    xcodebuild \
        -exportArchive \
        -archivePath "$ARCHIVE_PATH" \
        -exportOptionsPlist "$EXPORT_PLIST" \
        -exportPath "$EXPORT_DIR" \
        -allowProvisioningUpdates
    [ -d "$APP_PATH" ] || fail "Export did not produce $APP_PATH"
}

read_version() {
    VERSION="$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$APP_PATH/Contents/Info.plist")"
    [ -n "$VERSION" ] || fail "Could not read CFBundleShortVersionString from the exported app"
    log "Version: $VERSION"
}

notarize() {
    log "Notarize (profile: $NOTARY_PROFILE)"
    local zip="$BUILD_DIR/StockAlerts.zip"
    rm -f "$zip"
    ditto -c -k --keepParent "$APP_PATH" "$zip"

    local out
    out="$(xcrun notarytool submit "$zip" --keychain-profile "$NOTARY_PROFILE" --wait 2>&1)"
    echo "$out"
    if ! grep -q "status: Accepted" <<<"$out"; then
        local id
        id="$(grep -m1 -E '^[[:space:]]*id:' <<<"$out" | awk '{print $2}')"
        fail "Notarization not Accepted. Read the log with:
  xcrun notarytool log ${id:-<submission-id>} --keychain-profile $NOTARY_PROFILE"
    fi
}

staple_app() {
    log "Staple the .app"
    xcrun stapler staple "$APP_PATH"
}

build_dmg() {
    log "Build DMG (create-dmg)"
    mkdir -p "$DIST_DIR"
    local dmg="$DIST_DIR/StockAlerts-$VERSION.dmg"
    rm -f "$dmg"
    create-dmg \
        --volname "Stock Alerts $VERSION" \
        --background "$BACKGROUND" \
        --window-size 540 380 \
        --icon-size 96 \
        --icon "StockAlerts.app" 140 190 \
        --app-drop-link 400 190 \
        --codesign "$SIGN_IDENTITY" \
        "$dmg" \
        "$APP_PATH"
}

staple_dmg() {
    log "Staple the DMG"
    xcrun stapler staple "$DIST_DIR/StockAlerts-$VERSION.dmg"
}

verify() {
    log "Verify (spctl)"
    spctl --assess --type install --verbose "$DIST_DIR/StockAlerts-$VERSION.dmg"
}

main() {
    preflight
    generate_project
    render_export_options
    archive
    export_app
    read_version
    notarize
    staple_app
    build_dmg
    staple_dmg
    verify
    echo
    log "Done: dist/StockAlerts-$VERSION.dmg"
}

main "$@"
