#!/bin/bash
# Run the StockAlerts test suite via xcodebuild.
#
# Wraps xcodebuild with the flags this project needs every time:
#   - Debug configuration
#   - macOS arm64 destination
#   - -allowProvisioningUpdates so development signing can refresh as needed
#
# Extra arguments are forwarded to xcodebuild. Example — run one test:
#   ./scripts/test.sh -only-testing:StockAlertsTests/KeychainStoreTests
#
# Requires:
#   - Local.xcconfig (copy from Local.xcconfig.example, set DEVELOPMENT_TEAM)
#   - StockAlerts.xcodeproj (generated by `xcodegen generate`)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

if [ ! -f "$REPO_ROOT/Local.xcconfig" ]; then
    cat >&2 <<EOF
Error: Local.xcconfig not found in $REPO_ROOT

  cp Local.xcconfig.example Local.xcconfig
  # then edit it to set DEVELOPMENT_TEAM to your Apple team ID

See README.md for details.
EOF
    exit 1
fi

if [ ! -d "$REPO_ROOT/StockAlerts.xcodeproj" ]; then
    cat >&2 <<EOF
Error: StockAlerts.xcodeproj not found.

Run:
  xcodegen generate
EOF
    exit 1
fi

cd "$REPO_ROOT"
exec xcodebuild \
    -project StockAlerts.xcodeproj \
    -scheme StockAlerts \
    -configuration Debug \
    -destination 'platform=macOS,arch=arm64' \
    -allowProvisioningUpdates \
    test \
    "$@"
